CREATE TABLE IF NOT EXISTS MediaFiles (
    FileID INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    FileName VARCHAR(255),
    UploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OwnerID INT,
    FOREIGN KEY (OwnerID)
        REFERENCES Users (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)