CREATE TABLE IF NOT EXISTS MediaFiles (
    FileID INT AUTO_INCREMENT PRIMARY KEY,
    [URL] VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OwnerID INT
    FOREIGN KEY (OwnerID)
        REFERENCES Users (UserID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)